spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      hibernate:
        format_sql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jwt:
    secret: cokebear1571024480

logging:
  level:
    org.hibernate.sql: info
